FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install software-properties-common
RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
RUN add-apt-repository 'deb http://mariadb.mirror.digitalpacific.com.au/repo/10.1/ubuntu xenial main'
RUN apt-get update

RUN apt -y install libffi-dev libssl-dev python-setuptools python-dev python-pip
RUN pip install ansible
RUN mkdir -p /etc/ansible

COPY docker/initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts